# Generated by Django 4.2 on 2023-05-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_spareparts_toolcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='toolDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
