# Generated by Django 4.2 on 2023-06-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_spareparts_tooldesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryImage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
