# Generated by Django 4.2 on 2023-06-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_galleryimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spareparts',
            old_name='toolTitle',
            new_name='name',
        ),
    ]
