# Generated by Django 4.2 on 2023-06-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_tooltitle_spareparts_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spareparts',
            old_name='toolPrice',
            new_name='price',
        ),
    ]
