# Generated by Django 4.2 on 2023-06-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_toolprice_spareparts_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spareparts',
            old_name='toolImage',
            new_name='image',
        ),
    ]
