# Generated by Django 4.2 on 2023-07-08 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_toolimage_spareparts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.spareparts')),
            ],
        ),
    ]
