# Generated by Django 4.2 on 2023-07-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
