# Generated by Django 4.2 on 2023-07-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_contact_name_remove_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instantquote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('do_you_need_financing', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('roaster_trade_in', models.CharField(max_length=100)),
                ('select_roaster_size1', models.CharField(max_length=100)),
                ('voltage', models.CharField(max_length=100)),
                ('select_roaster_type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('gas_type', models.CharField(max_length=100)),
                ('first_responder', models.CharField(max_length=100)),
            ],
        ),
    ]
