# Generated by Django 4.2 on 2023-07-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_contact_name_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantquote',
            name='color',
            field=models.CharField(choices=[('Gloss Black', 'Gloss Black'), ('Gloss White', 'Gloss White'), ('Matte Black', 'Matte Black'), ('Matte White', 'Matte White'), ('Design Package ($2450.00 USD*)', 'Design Package ($2450.00 USD*)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instantquote',
            name='do_you_need_financing',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instantquote',
            name='first_responder',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instantquote',
            name='gas_type',
            field=models.CharField(choices=[('Natural Gas', 'Natural Gas'), ('Propane ($300.00 USD*)', 'Propane ($300.00 USD*)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instantquote',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instantquote',
            name='roaster_trade_in',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instantquote',
            name='select_roaster_size1',
            field=models.CharField(choices=[('Genesis-Xr3', 'Genesis-Xr3'), ('Ranger-Xr5', 'Ranger-Xr5'), ('Raven-Xr15', 'Raven-Xr15'), ('Sentinel-Xr20', 'Sentinel-Xr20'), ('Warden-Xr30', 'Warden-Xr30')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instantquote',
            name='select_roaster_type',
            field=models.CharField(choices=[('Barley Roaster', 'Barley Roaster'), ('Cacao Roaster', 'Cacao Roaster'), ('Chili Roaster', 'Chili Roaster'), ('Coffee Roaster', 'Coffee Roaster'), ('Grape Seed Roaster', 'Grape Seed Roaster'), ('Hemp Roaster', 'Hemp Roaster'), ('Millet Roaster', 'Millet Roaster'), ('Noodle Roaster', 'Noodle Roaster'), ('Nut Roaster', 'Nut Roaster'), ('Sesame Seed Roaster', 'Sesame Seed Roaster'), ('Woodchip Roaster', 'Woodchip Roaster')], max_length=100),
        ),
        migrations.AlterField(
            model_name='instantquote',
            name='voltage',
            field=models.CharField(choices=[('110 V', '110 V'), ('220 V', '220 V')], max_length=100),
        ),
    ]
