# Generated by Django 4.2 on 2023-07-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_videofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videoFile',
        ),
    ]
