# Generated by Django 4.2 on 2023-08-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_videofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofiles',
            name='video_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
