# Generated by Django 4.2 on 2023-08-01 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_videofiles_video_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videoFiles',
        ),
    ]
