# Generated by Django 4.2 on 2023-08-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_delete_videofiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media')),
                ('video_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
